name: PH Collation Monthly

# Controls when the workflow will run
on:
  schedule:
    - cron: '00 16 1 * *'
  workflow_dispatch:

jobs:
  run-python-script:
    runs-on: ubuntu-latest
    steps:

      - name: checkout repo content
        uses: actions/checkout@v4 # checkout the repository content

      - name: setup python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11' # install the python version needed
      
      - name: Create .env file
        run: |
          echo "SLACK_TOKEN=${{ secrets.SLACK_TOKEN }}" >> .env
          echo "SLACK_CHANNEL=${{ secrets.SLACK_CHANNEL }}" >> .env
          echo "CACHE_CHANNEL=${{ secrets.CACHE_CHANNEL }}" >> .env

      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: execute py script
        run: python -m ph_checks.collate
  